spring.application.name=indietracks-backend
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/indietracks
spring.datasource.username=postgres
spring.datasource.password=54610
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis-Plus
mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.map-null-to-empty-string=false

# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=indietracks_app
minio.secret-key=indietracks_app_2026
minio.bucket=indietracks
minio.presigned-expiry=7200
